export const kgWeights = [
    { value: '-' },
    { value: '2.5 kg' },
    { value: '5 kg' },
    { value: '7.5 kg' },
    { value: '10 kg' },
    { value: '15 kg' },
    { value: '20 kg' },
    { value: '25 kg' },
    { value: '30 kg' },
    { value: '35 kg' },
    { value: '40 kg' },
    { value: '45 kg' },
    { value: '50 kg' },
    { value: '55 kg' },
    { value: '60 kg' },
    { value: '65 kg' },
    { value: '70 kg' },
    { value: '75 kg' },
    { value: '80 kg' },
    { value: '85 kg' },
    { value: '90 kg' },
    { value: '95 kg' },
    { value: '100 kg' }
]