export const lbsWeights = [
    { value: '-' },
    { value: '5 lbs' },
    { value: '10 lbs' },
    { value: '15 lbs' },
    { value: '20 lbs' },
    { value: '30 lbs' },
    { value: '40 lbs' },
    { value: '50 lbs' },
    { value: '60 lbs' },
    { value: '70 lbs' },
    { value: '80 lbs' },
    { value: '90 lbs' },
    { value: '100 lbs' },
    { value: '110 lbs' },
    { value: '120 lbs' },
    { value: '130 lbs' },
    { value: '140 lbs' },
    { value: '150 lbs' },
    { value: '160 lbs' },
    { value: '170 lbs' },
    { value: '180 lbs' },
    { value: '290 lbs' },
    { value: '200 lbs' }
]